// Per-agent deck content. Every figure traces to ../gtm/HPP-DECK-SOURCES.md.
module.exports = [
{
  code:"HPP-01", name:"Revenue-Cycle & Denial Management", file:"HPP-01-Revenue-Cycle-Denial",
  gate:"Denials Specialist",
  sub:"Reviews claims, classifies denials, drafts grounded appeals, tracks payer responses — a denials specialist submits.",
  issue:"Initial denials are rising while rework stays manual and expensive — so a large share of denied dollars is simply abandoned.",
  stats:[{num:"~11.8%",cap:"initial claim denial rate (2024) and climbing; 41% of providers report >10%"},
         {num:"~$18B",cap:"U.S. hospital spend in 2025 overturning denials (of ~$43B on billing & collections)"},
         {num:"35–60%",cap:"of denied claims are never reworked — permanent, avoidable revenue loss"}],
  statsrc:"Sources: Experian Health, State of Claims 2025 [industry-research]; rework $25–$181/claim.",
  situation:["CO-197 (auth), CO-50 (necessity), CO-16 (coding) denials pile up faster than staff can rework them.",
    "Rework is labor-intensive (~$25–$181 per claim); the cheapest denials get worked, the rest written off.",
    "Smaller systems lag: ~20% have adopted gen-AI RCM vs 64% of large systems (cost is the top barrier)."],
  market:["~40% of health systems are piloting/implementing gen AI in revenue cycle; 39% more are exploring.",
    "Autonomous coding is delivering: Inova reported −$500K coding cost, −50% DNFB, +10% charge capture.",
    "90% of rev-cycle leaders expect gen AI to play a bigger role in coding operations."],
  constraint:"AI triages, classifies, and drafts the appeal; a denials specialist approves — and a biller, not the agent, ever submits a claim.",
  steps:["load_claim","analyze_denial","gather_evidence","draft_appeal","compliance_check"],
  features:[{t:"Grounded appeals",d:"Every code, amount, and policy in the appeal traces to the claim or approved coverage policy — or grounding fails it."},
    {t:"Root-cause routing",d:"CARC/RARC codes map to appeal · correct-and-resubmit · escalate, so the right work goes to the right queue."},
    {t:"Submission is human",d:"clearinghouse.submit_claim is withheld from the agent; the appeal is submitted only on specialist approval."}],
  systems:"Patient accounting · Clearinghouse (X12 837/277) · Payer portal · Encoder · EHR/FHIR",
  bright:"The agent never submits a claim — `clearinghouse.submit_claim` is withheld; a biller submits.",
  why:["Attacks both rework unit cost and the 35–60% never-reworked leakage at once.",
    "Cleanest, most measurable CFO ROI in the building — the recommended initial wedge.",
    "Every appeal is grounded, PHI-masked-audited, and submitted only after specialist approval.",
    "Compounds with Agents 04/06, which prevent the front-end and coding denials upstream."],
  outcome:["Faster, consistent denial triage","Grounded, policy-cited appeals in seconds",
    "Less abandoned revenue","Auditable trail for every touch"],
  whysrc:"Stakes: Experian 2025; Inova/AKASA. Maturity: Demonstrated + Deployable-by-design."
},
{
  code:"HPP-02", name:"Prior-Authorization", file:"HPP-02-Prior-Authorization",
  gate:"PA Nurse",
  sub:"Determines payer requirements, assembles evidence, evaluates criteria, monitors status — a PA nurse submits.",
  issue:"Prior authorization is high-volume, manual, and a leading cause of care delays and clinician burnout.",
  stats:[{num:"~39 / wk",cap:"prior auths per physician (~13 hours); 40% have staff working only on PA"},
         {num:"94%",cap:"of physicians say PA delays necessary care; 78% report treatment abandonment"},
         {num:"Jan 2027",cap:"CMS-0057-F deadline for payer FHIR Prior-Authorization APIs"}],
  statsrc:"Sources: AMA 2024 Prior-Auth physician survey [association]; CMS-0057-F [gov].",
  situation:["Coordinators re-key the same clinical evidence across payer portals and fax; status is opaque.",
    "Delays drive abandonment (78%) and burnout (89% say PA contributes); urgent cases get stuck in the same queue.",
    "Payers and CMS are forcing change: CMS-0057-F mandates four FHIR APIs (incl. Prior Auth) by Jan 1, 2027."],
  market:["70% of health plans are prioritizing agentic AI for UM, prior auth, and claims (Deloitte).",
    "June 2025: 50+ health plans pledged real-time approval for ≥80% of requests and faster turnaround.",
    "93% of plan execs expect AI to ease prior authorization."],
  constraint:"AI determines the requirement, assembles the packet, and submits behind a nurse gate — but the coverage determination is always the payer's.",
  steps:["check_requirement","gather_evidence","evaluate_criteria","assemble_packet","compliance_check"],
  features:[{t:"Da Vinci-aligned",d:"CRD requirement check, DTR/PAS packet assembly, 278/status monitoring — the FHIR surfaces CMS standardizes by 2027."},
    {t:"Criteria-grounded",d:"MCG/InterQual indications and medical-necessity policy are cited; nothing is fabricated."},
    {t:"Urgent escalation",d:"Expedited cases are routed fast; missing evidence returns a request, not a guess."}],
  systems:"Payer (Da Vinci CRD/DTR/PAS, X12 278) · MCG/InterQual · EHR/FHIR · IDP",
  bright:"The agent submits a PA request behind a human gate — but the coverage determination is the payer's, never the agent's.",
  why:["Compresses the ~13 hours/week physicians lose to PA and the staff time behind it.",
    "Positions providers and plans for the CMS-0057-F 2027 FHIR mandate now.",
    "Reduces care delays and the downstream CO-197 denials Agent 01 works.",
    "Every rationale is grounded and submitted only on PA-nurse approval."],
  outcome:["Lower authorization cycle time","Fewer care delays / abandonment",
    "CMS-0057-F readiness","Consistent, cited clinical rationales"],
  whysrc:"Sources: AMA 2024; Deloitte Sep 2025; CMS-0057-F. Maturity: Demonstrated + Deployable-by-design."
},
{
  code:"HPP-03", name:"Clinical-Administration", file:"HPP-03-Clinical-Administration",
  gate:"Clinician Sign-off",
  sub:"Summarizes charts, prepares visits, coordinates referrals, drafts discharge documentation — a clinician signs.",
  issue:"Documentation and inbox burden are leading drivers of clinician burnout and after-hours 'pajama time'.",
  stats:[{num:"51.9%→38.8%",cap:"ambulatory burnout after 30 days with an ambient AI scribe (263 clinicians, 6 systems)"},
         {num:"~30 min/day",cap:"documentation time saved per provider (UW Health); >15% less note-composition time"},
         {num:"+0.49",cap:"additional visits per week per clinician associated with ambient AI documentation"}],
  statsrc:"Sources: JAMA 2025 ambient-AI QI study; AHA; UChicago Medicine [peer-reviewed].",
  situation:["Clinicians spend hours composing notes, summarizing charts, and clearing the in-basket after clinic.",
    "Care transitions and referrals are assembled manually and late, risking gaps at handoff.",
    "Info-blocking rules (21st Century Cures) require timely EHI access — summaries must surface, not withhold."],
  market:["Ambient AI scribes are scaling fast: measured burnout drops, ~30 min/day saved, more visits.",
    ">80% of health-system execs are prioritizing agentic AI for clinical operations and care delivery.",
    "Leading systems pair ambient capture with governed drafting that a clinician reviews and signs."],
  constraint:"AI drafts the summary, note, referral, or discharge doc; a licensed clinician reviews and signs — the agent never enters orders.",
  steps:["load_chart","check_consent","produce_artifact","compliance_check"],
  features:[{t:"Drafts, never signs",d:"ehr.draft_note files a DRAFT for clinician sign-off; the agent holds no order-entry or signing authority."},
    {t:"42 CFR Part 2 aware",d:"A SUD-sensitive record without consent never produces an artifact — it escalates."},
    {t:"Chart-grounded",d:"Every problem, med, result, and date traces to the chart; patient-facing text meets a health-literacy bar."}],
  systems:"EHR/FHIR (HealthLake, Comprehend Medical) · Care plan · Scheduling · Consent",
  bright:"Clinical artifacts are drafts a clinician signs — `ehr.draft_note` is a gated draft; no order entry, no autonomous signing.",
  why:["Recovers measurable clinician capacity and reduces after-hours documentation.",
    "Surfaces lawful EHI on time — aligned with 21st Century Cures info-blocking rules.",
    "Sensitive (Part 2) and patient-facing content is gated and health-literacy-checked.",
    "Every draft is grounded in the chart and signed by a licensed human."],
  outcome:["Less documentation / inbox burden","Cleaner, timelier care transitions",
    "Clinician-signed, grounded notes","Consent-safe handling of sensitive data"],
  whysrc:"Sources: JAMA 2025; Deloitte Sep 2025. Maturity: Demonstrated + Deployable-by-design."
},
{
  code:"HPP-04", name:"Patient Access", file:"HPP-04-Patient-Access",
  gate:"Access Rep",
  sub:"Scheduling, registration, benefits verification, Good Faith Estimates, referral status — a rep approves writes.",
  issue:"Access friction drives no-shows and front-end errors that become the denials revenue cycle later reworks.",
  stats:[{num:"23–33%",cap:"typical U.S. outpatient no-show rate; avg cost ~$200 per missed appointment"},
         {num:"~$150B",cap:"estimated annual cost of missed appointments to the U.S. healthcare system"},
         {num:"GFE",cap:"No Surprises Act Good Faith Estimate required for self-pay / uninsured patients"}],
  statsrc:"Sources: Curogram / Dialog Health / MGMA 2024–2025 [industry-research]; No Surprises Act [gov].",
  situation:["Eligibility and registration errors are a top upstream cause of downstream denials (e.g., terminated coverage).",
    "No-shows and unclear cost drive leakage; patients want a fast booking and an honest estimate.",
    "The No Surprises Act requires a Good Faith Estimate — a compliance obligation, not a nicety."],
  market:["Practices add reminders, no-show fees, and self-scheduling; AI handles routine access tasks.",
    "Amazon Connect Health adds conversational identity verification and natural-language appointment management.",
    "Leaders verify identity first and produce deterministic estimates — not LLM-guessed prices."],
  constraint:"AI verifies identity, checks eligibility, and produces a deterministic Good Faith Estimate; a rep approves before any booking or registration.",
  steps:["verify_identity","check_eligibility","estimate_cost","get_availability","prepare_summary","compliance_check"],
  features:[{t:"Estimate is deterministic",d:"The Good Faith Estimate comes from a rules tool (NSA basis + disclaimer), never the LLM."},
    {t:"Identity before disclosure",d:"No account or benefit detail is shared without a verified member identity."},
    {t:"Prevents denials upstream",d:"Catches coverage/registration issues at the front door — cheaper than appealing them later."}],
  systems:"Scheduling · Registration · Payer eligibility (X12 270/271) · Identity",
  bright:"The cost estimate is a deterministic Good Faith Estimate tool — never the LLM; no disclosure without verified identity.",
  why:["Pays back twice: fewer no-shows and fewer front-end denials (compounding with Agent 01).",
    "Meets the No Surprises Act GFE obligation with a deterministic, auditable estimate.",
    "Member-facing text is held to a 6th–8th grade health-literacy bar (Section 1557).",
    "Booking and registration commit only on a verified access-rep approval."],
  outcome:["Fewer no-shows and leakage","Fewer front-end denials downstream",
    "Compliant Good Faith Estimates","Identity-safe member disclosure"],
  whysrc:"Sources: Curogram/MGMA 2024–25; Amazon Connect Health. Maturity: Demonstrated + Deployable-by-design."
},
{
  code:"HPP-05", name:"Utilization Management", file:"HPP-05-Utilization-Management",
  gate:"Medical Director",
  sub:"Applies clinical criteria, screens for disparate impact, prepares a recommendation — the medical director decides.",
  issue:"Utilization management is high-volume and under intense regulatory and legal scrutiny over algorithmic denials.",
  stats:[{num:"8.7%→22.7%",cap:"one insurer's post-acute denial rate after deploying an AI tool (2019–2022, Senate report)"},
         {num:"~82%",cap:"overturn-on-appeal rate cited for some AI prior-auth/denial tools"},
         {num:"70%",cap:"of health plans prioritizing agentic AI for UM, prior auth, and claims (Deloitte)"}],
  statsrc:"Sources: U.S. Senate PSI 2024; AI-PA litigation; Deloitte Sep 2025 [gov]/[industry-research].",
  situation:["Algorithmic UM is in the headlines: lawsuits over AI-driven post-acute denials and high overturn rates.",
    "CMS launched the WISeR model (July 2025, 6 states) tracking overturned-denial rates as a benchmark.",
    "CMS is explicit: AI may assist, but a human must make the Medicare Advantage coverage determination."],
  market:["Plans want UM efficiency but cannot accept algorithmic denials — the governance gap is the blocker.",
    "Defensible programs apply criteria with AI and keep the determination with a medical director.",
    "Fairness screening and audit trails are becoming table stakes for any AI-in-UM deployment."],
  constraint:"AI applies criteria and recommends; the medical director decides. issue_determination is withheld from EVERY agent — an adverse recommendation is forwarded, never auto-denied.",
  steps:["gather_clinical","evaluate_criteria","fairness_screen","draft_recommendation","compliance_check"],
  features:[{t:"Determination withheld",d:"No agent holds payer.issue_determination; even a director session can't issue one THROUGH the agent (tested)."},
    {t:"Four-fifths fairness",d:"An EEOC four-fifths screen flags disparate selection rates on the flag/rank step for human review."},
    {t:"Never auto-denies",d:"A 'does not meet' recommendation is forwarded to the medical director — coverage is a human decision."}],
  systems:"MCG/InterQual · Coverage (LCD/NCD) · Payer · EHR/FHIR",
  bright:"`payer.issue_determination` is withheld from every agent; an adverse recommendation is forwarded for a human determination, never auto-denied.",
  why:["This is the control that makes an AI-in-UM program defensible under CMS scrutiny.",
    "Criteria application is consistent, cited, and fairness-screened — and auditable for regulators.",
    "The medical director owns every determination; the agent only summarizes evidence against criteria.",
    "Directly answers the litigation and Senate-report concerns about algorithmic denial."],
  outcome:["Faster, consistent criteria review","Fairness-screened, auditable record",
    "Determination stays human","Defensible under CMS / 1557"],
  whysrc:"Sources: Senate PSI 2024; CMS WISeR 2025; Deloitte. Maturity: Demonstrated + Deployable-by-design."
},
{
  code:"HPP-06", name:"Payment Integrity & Coding", file:"HPP-06-Payment-Integrity-Coding",
  gate:"Payment-Integrity Reviewer",
  sub:"Validates codes (NCCI/MUE), checks medical necessity, flags overpayments and duplicates — a reviewer confirms.",
  issue:"Improper payments and coding defects run to tens of billions a year — and drive both denials and False Claims Act exposure.",
  stats:[{num:"$28.8B / $37.4B",cap:"FY2025 Medicare FFS / Medicaid improper payments (6.55% / 6.12%)"},
         {num:"~$40B",cap:"Medicare Advantage overpayment attributed to coding differences (MedPAC 2025)"},
         {num:"22.3 : 1",cap:"FY2025 Medicare program-integrity ROI (savings $26.3B → $41.9B, +59%)"}],
  statsrc:"Sources: CMS FY2025 Improper Payments Fact Sheet; MedPAC 2025 [gov].",
  situation:["Coding defects are a leading denial root cause (CO-16/CO-11) and a False Claims Act / OIG exposure surface.",
    "77% of Medicaid improper payments are insufficient documentation — a documentation problem, not always fraud.",
    "Payers and providers both need pre- and post-pay integrity review at scale."],
  market:["Program-integrity ROI is at a record 22.3:1; CMS is leaning into data-driven FWA review.",
    "Autonomous coding and edit engines (NCCI/MUE) surface upcoding, bundling, and duplicates.",
    "The defensible pattern: surface a flag for a human reviewer — never an automated recoupment."],
  constraint:"AI validates codes and flags overpayment, upcoding, duplicates, and unsupported necessity; a payment-integrity reviewer confirms — the agent never recoups or submits.",
  steps:["load_claim","analyze_coding","detect_issues","draft_finding","compliance_check"],
  features:[{t:"Flags, never acts",d:"No recoupment, payment adjustment, or claim submission — submit_claim is withheld; the agent records a review flag."},
    {t:"Edit-grounded",d:"NCCI/MUE results, the documentation-supported codes, and coverage policy back every finding."},
    {t:"A flag, not a verdict",d:"A mismatch is a prompt for a human reviewer to confirm — never an assertion of fraud."}],
  systems:"Encoder (NCCI/MUE, DRG) · Patient accounting · Clearinghouse · EHR/FHIR",
  bright:"The agent flags only — no recoupment, payment adjustment, or claim submission. A mismatch is a flag for review, never proof.",
  why:["Two-sided value: fewer coding-driven denials for providers, surfaced recoveries for payers.",
    "Lowers False Claims Act exposure by catching upcoding and unsupported necessity pre-bill.",
    "Every finding is grounded in edits and documentation; a human confirms before any action.",
    "Compounds with Agent 01 — coding defects are a top denial root cause."],
  outcome:["Fewer coding-driven denials","Surfaced overpayments / duplicates",
    "Lower FCA / OIG exposure","Human-confirmed, audited flags"],
  whysrc:"Sources: CMS FY2025; MedPAC. Maturity: Demonstrated + Deployable-by-design."
},
{
  code:"HPP-07", name:"Care Management & Population Health", file:"HPP-07-Care-Management",
  gate:"Care Manager",
  sub:"Identifies care gaps, stratifies risk (HCC/RAF), surfaces SDOH, prepares outreach — a care manager owns the plan.",
  issue:"Value-based programs depend on closing care gaps and accurate risk capture — but ungoverned risk models can be biased.",
  stats:[{num:">half",cap:"reduction in Black patients flagged for extra care by a widely used biased risk algorithm (Science 2019)"},
         {num:"26.3%",cap:"more chronic conditions in Black vs equally-ranked white patients under that algorithm"},
         {num:">80%",cap:"of health-system execs prioritizing agentic AI for care delivery (Deloitte)"}],
  statsrc:"Sources: Obermeyer et al., Science 2019 [peer-reviewed]; Deloitte Sep 2025 [industry-research].",
  situation:["Care-gap closure and accurate HCC/RAF capture drive Stars/quality bonuses and value-based payment.",
    "A landmark study showed a widely used cost-based risk model systematically under-served Black patients.",
    "Ungoverned risk stratification raises Section 1557 nondiscrimination and risk-adjustment-integrity concerns."],
  market:["Predictive risk and care-gap models are a competitive necessity for Stars bonus payments.",
    "But adoption now demands fairness screening and explainability — the 2019 bias case is the cautionary tale.",
    "Leaders pair gap identification with a four-fifths fairness check and a care manager who owns the plan."],
  constraint:"AI identifies gaps, stratifies risk, and drafts outreach with a four-fifths fairness screen; the care manager signs off and owns the plan.",
  steps:["load_patient","check_consent","identify_gaps","fairness_screen","draft_artifacts","compliance_check"],
  features:[{t:"Fairness-screened",d:"A four-fifths disparate-impact screen runs on the risk-stratification step — a flagged rate goes to human review."},
    {t:"42 CFR Part 2 aware",d:"A SUD-sensitive record without consent never produces outreach — it escalates."},
    {t:"Care manager owns it",d:"Care-plan writes are gated; outreach is plain-language; the human decides and owns the plan."}],
  systems:"Care management (HCC/RAF) · EHR/FHIR (HealthLake) · Consent",
  bright:"Risk stratification is fairness-screened and care-plan writes are gated; the care manager owns the plan — the agent never assigns risk autonomously.",
  why:["Closes care gaps and supports accurate risk capture — the engine of value-based revenue.",
    "Directly addresses the 2019 algorithmic-bias case with a built-in four-fifths fairness screen.",
    "Section 1557 and risk-adjustment integrity are defended by fairness + grounding + human ownership.",
    "Sensitive (Part 2) records are gated; patient outreach is health-literacy-checked."],
  outcome:["More closed care gaps (Stars)","Fairer, auditable risk stratification",
    "Defensible under Section 1557","Care-manager-owned plans"],
  whysrc:"Sources: Science 2019; Deloitte. Maturity: Demonstrated + Deployable-by-design."
},
{
  code:"HPP-08", name:"Contact Center / Member Services", file:"HPP-08-Contact-Center-Member-Services",
  gate:"Member-Services Rep",
  sub:"Answers member inquiries, checks claim status and benefits, intakes grievances on Amazon Connect — a rep approves writes.",
  issue:"Member-service volume spikes around denials and benefits questions — and healthcare live-agent calls are expensive.",
  stats:[{num:"$25–$35",cap:"cost of a healthcare live-agent call/ticket (vs $6–$15 in general industries)"},
         {num:"~45%",cap:"of routine member queries AI agents can deflect (2025 CX benchmark)"},
         {num:"−45% / +12 pt",cap:"one healthcare group's contact-center cost cut and satisfaction gain with Amazon Connect AI"}],
  statsrc:"Sources: Hyro State of Healthcare Call Centers 2025; D3Clarity / Amazon Connect [industry-research]/[sector-press].",
  situation:["Members call about the same denials and benefits questions the rest of the suite touches — at $25–$35 a call.",
    "Reps need verified context fast; identity proofing and account lookups eat handle time.",
    "Section 1557 requires accessible, nondiscriminatory, plain-language member communication."],
  market:["AI agents now deflect ~45% of routine queries (status, benefits, scheduling), cutting cost per call.",
    "Amazon Connect Health adds conversational identity verification + appointment management.",
    "One healthcare group cut contact-center cost ~45%/yr and raised satisfaction 12 points with Connect AI."],
  constraint:"AI verifies the member, retrieves status and benefits, and drafts a plain-language answer; a rep approves logging or grievance intake — and the agent never submits an appeal.",
  steps:["verify_member","retrieve","draft_response","compliance_check"],
  features:[{t:"Identity before disclosure",d:"No account, claim, or benefit detail is shared without a verified member."},
    {t:"Grounded answers",d:"Claim status (276/277) and eligibility (270/271) responses are grounded; nothing is fabricated."},
    {t:"Hands off, doesn't decide",d:"Cannot submit an appeal (that's Agent 01); grievance intake routes to the human process."}],
  systems:"Amazon Connect · Payer (X12 276/277, 270/271) · Identity · Consent",
  bright:"No account disclosure without a verified member; the agent cannot submit an appeal — it hands off to revenue cycle.",
  why:["Deflects routine, expensive calls with grounded, identity-verified answers.",
    "Improves member experience (CAHPS/Stars) with plain-language, Section 1557-accessible responses.",
    "Logging and grievance intake are gated; every disclosure is identity-verified and audited.",
    "Closes the loop with Agent 01 — the same denials, answered for the member."],
  outcome:["Lower cost per call / deflection","Better member experience (Stars)",
    "Identity-safe, grounded answers","Compliant grievance intake"],
  whysrc:"Sources: Hyro 2025; Amazon Connect. Maturity: Demonstrated + Deployable-by-design."
}
];
